### ISSUE TITLE
Alignment is no longer working with the new release

### ISSUE THREAD

**Issue by azawawi** [adrianlee44/atom-aligner-python#2]
I am having a similar problem to https://github.com/adrianlee44/atom-aligner/issues/68 since the new release. Even a normal `=` alignment is not working without a downgrade.

The following is not working:

```python
a = "a"
ab = "ab"
abc = "abc"
```
**Installed Package Versions:**
```
aligner-python  1.0.2
aligner         1.0.2
```

**Comment by adrianlee44** [comment]
`=` used to be covered in the basic config but I never added `=` to python specific package. I have updated the package and should work with v1.1.0

**Comment by azawawi** [comment]
Working perfectly. Thanks 👍
