### ISSUE TITLE
Add support for comma alignment

### ISSUE THREAD

**Issue by goi42** [adrianlee44/atom-aligner-python#3]
I often like to have my commas aligned in python, e.g.,
```python
parser.add_argument('SIGNAL_NAME', nargs='?', default='FilterTest')
parser.add_argument('EVENT_TYPE' , nargs='?', default='FilterTest')
```
I'd find it very useful if comma alignment were also supported, preferably even for multiple commas in the lines

**Comment by adrianlee44** [comment]
Unfortunately, it seems like the python grammar at the moment doesn't parse the "," in your use case. To fully support this, https://github.com/atom/language-python would need to be updated first.
